name: boin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  font_awesome_flutter: ^9.0.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.3
  firebase_messaging: ^14.7.19
  provider: ^6.1.2
  flutter_custom_clippers: ^2.1.0
  syncfusion_flutter_charts: ^25.2.3+1
  
  csv: ^6.0.0
  
  file_picker: ^7.0.0
  excel: ^4.0.3
  vm_service: ^13.0.0
  expandable_text: ^2.3.0
  fl_chart: ^0.68.0
  rxdart: ^0.27.7
  url_launcher: ^6.2.6
  flutter_email_sender: ^6.0.3
  permission_handler: ^11.3.1
  mailto: ^2.0.0
  flutter_launch_store: ^1.0.6
  
  
  
  

dev_dependencies:
 
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/selog.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/selog.png"  # Ganti dengan path ke file ikon Anda
  min_sdk_android: 21
