// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCel91yBu6sozTQGW2Y1we5uKdOwFB3rKk',
    appId: '1:933716608805:web:141e10bb8a39d55c357ccc',
    messagingSenderId: '933716608805',
    projectId: 'boin-f5684',
    authDomain: 'boin-f5684.firebaseapp.com',
    databaseURL: 'https://boin-f5684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'boin-f5684.appspot.com',
    measurementId: 'G-CYMNDJF0NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ScpVUE9b2QPl5H0bAfY6PbPHB5hSgLM',
    appId: '1:933716608805:android:85b2bd1f234ddb94357ccc',
    messagingSenderId: '933716608805',
    projectId: 'boin-f5684',
    databaseURL: 'https://boin-f5684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'boin-f5684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkWf_edq80w5uMWiFbuxUbl9JGGQw3No',
    appId: '1:933716608805:ios:bc15d7a26f59e0a5357ccc',
    messagingSenderId: '933716608805',
    projectId: 'boin-f5684',
    databaseURL: 'https://boin-f5684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'boin-f5684.appspot.com',
    iosBundleId: 'com.example.boin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdkWf_edq80w5uMWiFbuxUbl9JGGQw3No',
    appId: '1:933716608805:ios:bc15d7a26f59e0a5357ccc',
    messagingSenderId: '933716608805',
    projectId: 'boin-f5684',
    databaseURL: 'https://boin-f5684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'boin-f5684.appspot.com',
    iosBundleId: 'com.example.boin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCel91yBu6sozTQGW2Y1we5uKdOwFB3rKk',
    appId: '1:933716608805:web:bb07bf2ffe555714357ccc',
    messagingSenderId: '933716608805',
    projectId: 'boin-f5684',
    authDomain: 'boin-f5684.firebaseapp.com',
    databaseURL: 'https://boin-f5684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'boin-f5684.appspot.com',
    measurementId: 'G-0LGR9XMQ4N',
  );

}